#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
STREAMER_DIR=$(cd -- "$SCRIPT_DIR/.." && pwd)

cd "$STREAMER_DIR"

if [[ ! -x ./holoteleop_camera_streamer ]]; then
  make -j"$(nproc)"
fi

export CAMERA_DEVICE=${CAMERA_DEVICE:-${WEBCAM_DEVICE:-/dev/video0}}
export CAMERA_INPUT_FORMAT=${CAMERA_INPUT_FORMAT:-${WEBCAM_INPUT_FORMAT:-H264}}
export CAMERA_TRANSPORT=${CAMERA_TRANSPORT:-${WEBCAM_TRANSPORT:-TCP}}
export CAMERA_WIDTH=${CAMERA_WIDTH:-${WEBCAM_WIDTH:-720}}
export CAMERA_HEIGHT=${CAMERA_HEIGHT:-${WEBCAM_HEIGHT:-1280}}
export CAMERA_FPS=${CAMERA_FPS:-${WEBCAM_FPS:-30}}
export CAMERA_BITRATE=${CAMERA_BITRATE:-${WEBCAM_BITRATE:-1500000}}
export CAMERA_TRANSCODE=${CAMERA_TRANSCODE:-${WEBCAM_TRANSCODE:-1}}
export CAMERA_OUTPUT_WIDTH=${CAMERA_OUTPUT_WIDTH:-${WEBCAM_OUTPUT_WIDTH:-540}}
export CAMERA_OUTPUT_HEIGHT=${CAMERA_OUTPUT_HEIGHT:-${WEBCAM_OUTPUT_HEIGHT:-960}}
export CAMERA_OUTPUT_FPS=${CAMERA_OUTPUT_FPS:-${WEBCAM_OUTPUT_FPS:-25}}
export CAMERA_CONTROL_PORT=${CAMERA_CONTROL_PORT:-13579}
export RECORD_CONTROL_PORT=${RECORD_CONTROL_PORT:-13600}
export CAMERA_UDP_FRAGMENT=${CAMERA_UDP_FRAGMENT:-${WEBCAM_UDP_FRAGMENT:-1}}
export CAMERA_UDP_MTU=${CAMERA_UDP_MTU:-${WEBCAM_UDP_MTU:-1200}}

exec ./holoteleop_camera_streamer
